### ISSUE TITLE
에러가 나서 문의드립니다.

### ISSUE THREAD

**Issue by ryanh9801** [nawnoes/dialogLM#16]
wellness.py 까지 잘 실행되고 train으로 넘어가려고
run_auto_regressive.py 와
run_text_classification.py를 실행하는 과정에서
앞의 것은 지금 학습중이라 어떻게 될지 모르겠지만
후자의 경우
"C:\Users\users\anaconda3\envs\pythonProject3\python.exe" "C:/Users/users/PycharmProjects/pythonProject3/wellness/train/run_text_classification.py"
Train(0):   0%|          | 0/1308 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/users/PycharmProjects/pythonProject3/wellness/train/run_text_classification.py", line 96, in <module>
    loss = train(device, epoch, model, optimizer, train_loader, save_step, save_ckpt_path, train_step)
  File "C:/Users/users/PycharmProjects/pythonProject3/wellness/train/run_text_classification.py", line 25, in train
    outputs = model(**data)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\users\PycharmProjects\pythonProject3\wellness\train\kobert.py", line 58, in forward
    inputs_embeds=inputs_embeds,
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\transformers\modeling_bert.py", line 753, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\transformers\modeling_bert.py", line 178, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

Process finished with exit code 1

의 에러가 나옵니다.

어디서 문제인지 감이 안와서 문의드립니다.
부탁드리겠습니다.
감사합니다.

**Comment by nawnoes** [comment]
안녕하세요.
```
File "C:\Users\users\PycharmProjects\pythonProject3\wellness\train\kobert.py", line 58, in forward
inputs_embeds=inputs_embeds,
File "C:\Users\users\anaconda3\envs\pythonProject3\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
보면 코버트에 입력으로 들어갈때 인덱스가 맞지 않는것 같은데 그부분 확인해보시면 어떨까합니다.
감사합니다:)

**Comment by ryanh9801** [comment]
해결되었습니다.
감사합니다.
